version: "3.7"
services:
  server:
    build:
      context: ./docker/server
      dockerfile: Dockerfile
    container_name: "${APP_NAME}-server"  
    restart: on-failure
    volumes:
      - "./project/:/var/www/html/project"
    networks:
      - devnet
    ports:
      - "${APP_PORT}:80"
      - "${APP_PORT_SSL}:443"
    depends_on:
      - db 
  db:
    image: mysql:8.0.27
    restart: always
    container_name: "${APP_NAME}-database" 
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}" 
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASS}"
      MYSQL_DATABASE: "${MYSQL_DB}"     
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/mysql/my.cnf:/etc/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - devnet 
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "${APP_NAME}-phpma"
    restart: on-failure
    environment:
      PMA_HOST: db
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_USER_PASS}"
    networks:
      - devnet   
    ports:
    - "${PHPMA_PORT}:80"
    depends_on:
      - db
networks:
    devnet:
      name: ${APP_NAME}
      driver: bridge
volumes:
  db-data:
    name: "${APP_NAME}_db-data"
